In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from keras.layers import Dense
from keras.models import Sequential

Using TensorFlow backend.


In [0]:
def assign_sex(row):
  if row['Sex']== 'male':
    return 1
  else:
    return 0
    

In [0]:
train_data=pd.read_csv("titanic.csv",sep=",")

In [4]:
train_data.head(5)

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [0]:
train_data=train_data.drop(['PassengerId','Name','Cabin','Embarked','Ticket','Fare'],axis=1)
train_data['Sex']=train_data.apply(assign_sex,axis=1)
train_data.fillna(0,inplace=True)

In [6]:
x=np.array(train_data.ix[:, 1: ])
y=np.ravel(train_data.Survived)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py:822: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  retval = getattr(retval, self.name)._getitem_axis(key, axis=i)


In [7]:
print(x)

[[ 3.  1. 22.  1.  0.]
 [ 1.  0. 38.  1.  0.]
 [ 3.  0. 26.  0.  0.]
 ...
 [ 3.  0.  0.  1.  2.]
 [ 1.  1. 26.  0.  0.]
 [ 3.  1. 32.  0.  0.]]


In [8]:
print(y)

[0 1 1 1 0 0 0 0 1 1 1 1 0 0 0 1 0 1 0 1 0 1 1 1 0 1 0 0 1 0 0 1 1 0 0 0 1
 0 0 1 0 0 0 1 1 0 0 1 0 0 0 0 1 1 0 1 1 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 0 0
 1 0 0 0 1 1 0 1 1 0 1 1 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 1 0 0 0 0 1 0 0 1 0 0 0 0 1 1 0 0 0 1 0
 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1
 0 1 1 0 0 1 0 1 1 1 1 0 0 1 0 0 0 0 0 1 0 0 1 1 1 0 1 0 0 0 1 1 0 1 0 1 0
 0 0 1 0 1 0 0 0 1 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 1 1
 1 0 1 0 0 0 0 0 1 1 1 0 1 1 0 1 1 0 0 0 1 0 0 0 1 0 0 1 0 1 1 1 1 0 0 0 0
 0 0 1 1 1 1 0 1 0 1 1 1 0 1 1 1 0 0 0 1 1 0 1 1 0 0 1 1 0 1 0 1 1 1 1 0 0
 0 1 0 0 1 1 0 1 1 0 0 0 1 1 1 1 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 1 1 1 1
 1 0 0 0 0 1 1 0 0 0 1 1 0 1 0 0 0 1 0 1 1 1 0 1 1 0 0 0 0 1 1 0 0 0 0 0 0
 1 0 0 0 0 1 0 1 0 1 1 0 0 0 0 0 0 0 0 1 1 0 1 1 1 1 0 0 1 0 1 0 0 1 0 0 1
 1 1 1 1 1 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 1 0
 0 0 1 1 0 1 0 0 1 0 0 0 

In [9]:
model=Sequential()
model.add(Dense(12,activation='relu', input_shape=(5,)))
model.add(Dense(8,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

In [0]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model.fit(x,y,epochs=10,batch_size=1,verbose=1)



Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where



Epoch 1/10





891/891 [==============================] - 2s 2ms/step - loss: 0.7747 - acc: 0.5421
Epoch 2/10
891/891 [==============================] - 1s 1ms/step - loss: 0.6699 - acc: 0.5791
Epoch 3/10
891/891 [==============================] - 1s 1ms/step - loss: 0.6278 - acc: 0.6375
Epoch 4/10
891/891 [==============================] - 1s 1ms/step - loss: 0.5991 - acc: 0.6712
Epoch 5/10
891/891 [==============================] - 1s 1ms/step - loss: 0.5733 - acc: 0.7149
Epoch 6/10
891/891 [==============================] - 1s 1ms/step - loss: 0.5402 - acc: 0.7542
Epoch 7/10
891/891 [==============================] - 1s 1ms/step - loss: 0.5214 - acc: 0.7755
Epoch 8/10
659/891 [=====================>........] - ETA: 0s - loss: 0.4823 - acc: 0.8088

In [0]:
scores = model.evaluate(x, y)
print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))